[package]
name = "math-eval"
version = "0.1.0"
edition = "2021"
default-run = "math-eval"
authors = ["Luka Pr≈°ina"]

[dependencies]
criterion = "0.3.5"
lazy_static = "1.4.0"
nom = "7.1.1"
ptree = "0.4.0"
ryu = "1.0.10"
smallvec = "1.8.0"
smartstring = "1.0.1"

[[bench]]
name = "general"
harness = false
